// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KGTUnrRWONInDN-b_rFxrnI3BXwhr-E',
    appId: '1:1091270013457:web:bc5b50cdedc4ed6db7f7b0',
    messagingSenderId: '1091270013457',
    projectId: 'pet-finder-11e54',
    authDomain: 'pet-finder-11e54.firebaseapp.com',
    storageBucket: 'pet-finder-11e54.firebasestorage.app',
    measurementId: 'G-E13GBTYEWW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC649YY4N_Mrd4XZfM1NfiVzUABa_pLhrI',
    appId: '1:1091270013457:ios:d6408170b26b804ab7f7b0',
    messagingSenderId: '1091270013457',
    projectId: 'pet-finder-11e54',
    storageBucket: 'pet-finder-11e54.firebasestorage.app',
    iosBundleId: 'com.example.animalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KGTUnrRWONInDN-b_rFxrnI3BXwhr-E',
    appId: '1:1091270013457:web:e4346eaf1f320656b7f7b0',
    messagingSenderId: '1091270013457',
    projectId: 'pet-finder-11e54',
    authDomain: 'pet-finder-11e54.firebaseapp.com',
    storageBucket: 'pet-finder-11e54.firebasestorage.app',
    measurementId: 'G-F3MSDR6QDV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC649YY4N_Mrd4XZfM1NfiVzUABa_pLhrI',
    appId: '1:1091270013457:ios:d6408170b26b804ab7f7b0',
    messagingSenderId: '1091270013457',
    projectId: 'pet-finder-11e54',
    storageBucket: 'pet-finder-11e54.firebasestorage.app',
    iosBundleId: 'com.example.animalApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiI1TCR4d3OvW9yewn_XwvczQ7AW8SdAE',
    appId: '1:1091270013457:android:6e638af8ca33bcb2b7f7b0',
    messagingSenderId: '1091270013457',
    projectId: 'pet-finder-11e54',
    storageBucket: 'pet-finder-11e54.firebasestorage.app',
  );

}