name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4  
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.35.0  
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'  

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze  

      - name: Run Tests with Coverage
        run: flutter test --coverage  

      - name: Build APK
        run: flutter build apk --release

      - name: List APK Files  
        run: ls build/app/outputs/flutter-apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_APP_CREDENTIALS }}  
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk